[package]
name = "mozart-runtime-constants"
description = "Constants used throughout the Mozart network."
edition = "2021"
license = "GPL-3.0-only"
version = "0.1.0"

[lints]
workspace = true

# FIXME: lock versions for all non-branched crates
[dependencies]
smallvec = "1.8.0"

frame-support = { workspace = true }
polkadot-primitives = { workspace = true }
polkadot-runtime-common = { workspace = true }
sp-runtime = { workspace = true }
sp-weights = { workspace = true }
sp-core = { workspace = true }

staging-xcm = { workspace = true }
staging-xcm-builder = { workspace = true }

[features]
default = ["std"]
std = [
	"frame-support/std",
	"polkadot-primitives/std",
	"polkadot-runtime-common/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-weights/std",
	"staging-xcm-builder/std",
	"staging-xcm/std",
]

# Set timing constants (e.g. session period) to faster versions to speed up testing.
fast-runtime = []
