keys = [
	"bin",
	"build-dependencies",
	"default",
	"dependencies",
	"dev-dependencies",
	"features",
	"lib",
	"name",
	"package",
	"std",
	"test",
	"workspace",
]

inline_keys = [
	"branch",
	"default-features",
	"features",
	"git",
	"optional",
	"package",
	"path",
	"rev",
	"version",
	"workspace",
]

sort_string_arrays = true
