[package]
name = "westend-emulated-chain"
description = "Westend emulated chain"
edition = "2021"
license = "GPL-3.0-only"
publish = false
version = "0.0.0"
[package.authors]
workspace = true

[lints]
workspace = true

[dependencies]
cumulus-primitives-core = { workspace = true }
emulated-integration-tests-common = { workspace = true }
pallet-staking = { workspace = true }
runtime-common = { workspace = true }
runtime-parachains = { workspace = true }
sc-consensus-grandpa = { workspace = true }
sp-consensus-babe = { workspace = true }
sp-consensus-beefy = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
tanssi-emulated-integration-tests-common = { workspace = true }
westend-runtime = { workspace = true }
westend-runtime-constants = { workspace = true }
xcm-emulator = { workspace = true }
