name: Publish Node docker image

inputs:
  tag:
    required: true
    type: string
  image:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Publish Node docker image
      shell: bash
      run: |
        DOCKER_IMAGE=moondancelabs/${{ inputs.image }}
        VERSION="${{ inputs.tag }}"
        CLEAN_VERSION="${VERSION%%-*}"
        COMMIT=`git rev-list -n 1 '${{ inputs.tag }}'`
        SHA=sha-${COMMIT::8}
        echo using "${DOCKER_IMAGE}:${SHA} as base image"

        echo building "${DOCKER_IMAGE}:${CLEAN_VERSION}"
        docker build \
          --build-arg DOCKER_IMAGE="$DOCKER_IMAGE" \
          --build-arg SHA="$SHA" \
          -f docker/${{ inputs.image }}.Dockerfile \
          -t "${DOCKER_IMAGE}:${CLEAN_VERSION}" \
          . 
        echo tagging "${DOCKER_IMAGE}:${CLEAN_VERSION}"
        docker push "${DOCKER_IMAGE}:${CLEAN_VERSION}"

          if [[ $CLEAN_VERSION =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            MINOR=${CLEAN_VERSION%.*}
            echo tagging "${DOCKER_IMAGE}:${MINOR}"
            docker tag "${DOCKER_IMAGE}:${CLEAN_VERSION}" "${DOCKER_IMAGE}:${MINOR}"
            docker push "${DOCKER_IMAGE}:${MINOR}"

            MAJOR=${MINOR%.*}
            echo tagging "${DOCKER_IMAGE}:${MAJOR}"
            docker tag "${DOCKER_IMAGE}:${CLEAN_VERSION}" "${DOCKER_IMAGE}:${MAJOR}"
            docker push "${DOCKER_IMAGE}:${MAJOR}"

            echo tagging "${DOCKER_IMAGE}:${SHA}"
            docker tag "${DOCKER_IMAGE}:${CLEAN_VERSION}" "${DOCKER_IMAGE}:${SHA}"
            docker push "${DOCKER_IMAGE}:${SHA}"

            echo tagging "${DOCKER_IMAGE}:latest"
            docker tag "${DOCKER_IMAGE}:${CLEAN_VERSION}" "${DOCKER_IMAGE}:latest"
            docker push "${DOCKER_IMAGE}:latest"
          fi
