[package]
name = "dancelight-system-emulated-network"
authors.workspace = true
edition = "2021"
license = "GPL-3.0-only"
version = "0.0.0"
description = "Dancelight System emulated bridged network"
publish = false

[lints]
workspace = true

[dependencies]
