[package]
name = "tp-container-chain-genesis-data"
authors = { workspace = true }
description = "Primitives related to container-chain genesis data"
edition = "2021"
license = "GPL-3.0-only"
version = "0.1.0"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[lints]
workspace = true

[dependencies]
hex = { workspace = true, optional = true, features = [ "alloc" ] }
hex-literal = { workspace = true }

log = { workspace = true }
serde = { workspace = true, features = [ "derive" ] }
serde_json = { workspace = true, optional = true }
tp-traits = { workspace = true }

# Substrate
frame-support = { workspace = true }
parity-scale-codec = { workspace = true }
scale-info = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true, optional = true }
sp-state-machine = { workspace = true, optional = true }
sp-std = { workspace = true }
sp-trie = { workspace = true, optional = true }

# Cumulus
cumulus-primitives-core = { workspace = true, optional = true }

# Polkadot
polkadot-primitives = { workspace = true, optional = true }

[features]
default = [ "std" ]
std = [
	"cumulus-primitives-core/std",
	"frame-support/std",
	"hex?/std",
	"log/std",
	"parity-scale-codec/std",
	"polkadot-primitives",
	"polkadot-primitives?/std",
	"scale-info/std",
	"serde/std",
	"serde/std",
	"serde_json?/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-state-machine/std",
	"sp-std/std",
	"sp-trie/std",
	"tp-traits/std",
]
json = [ "hex", "serde_json" ]
