[package]
name = "dancebox-runtime-test-utils"
description = "Dancelight runtime test utils"
edition = "2021"
license = "GPL-3.0-only"
publish = false
version = "0.0.0"
[package.authors]
workspace = true

[lints]
workspace = true

[dependencies]
cumulus-pallet-parachain-system = { workspace = true }
cumulus-primitives-core = { workspace = true }
cumulus-primitives-parachain-inherent = { workspace = true }
cumulus-test-relay-sproof-builder = { workspace = true }
dancebox-runtime = { workspace = true }
dp-consensus = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
nimbus-primitives = { workspace = true }
pallet-async-backing = { workspace = true }
pallet-author-inherent = { workspace = true }
pallet-authority-mapping = { workspace = true }
pallet-data-preservers = { workspace = true }
pallet-registrar = { workspace = true }
pallet-registrar-runtime-api = { workspace = true }
parity-scale-codec = { workspace = true, features = [ "derive" ] }
polkadot-parachain-primitives = { workspace = true }
scale-info = { workspace = true, features = [ "derive" ] }
sp-consensus-aura = { workspace = true }
sp-consensus-slots = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
tp-data-preservers-common = { workspace = true }

[features]
default = [
	"std",
]
std = [
	"cumulus-pallet-parachain-system/std",
	"cumulus-primitives-core/std",
	"cumulus-primitives-parachain-inherent/std",
	"cumulus-test-relay-sproof-builder/std",
	"dancebox-runtime/std",
	"dp-consensus/std",
	"frame-support/std",
	"frame-system/std",
	"nimbus-primitives/std",
	"pallet-async-backing/std",
	"pallet-author-inherent/std",
	"pallet-authority-mapping/std",
	"pallet-data-preservers/std",
	"pallet-registrar-runtime-api/std",
	"pallet-registrar/std",
	"parity-scale-codec/std",
	"polkadot-parachain-primitives/std",
	"scale-info/std",
	"sp-consensus-aura/std",
	"sp-consensus-slots/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
	"tp-data-preservers-common/std",
]
