name: changes-check
description: |
  Check if only non-build files changed (e.g. smoke tests or docs)

inputs: {}
outputs:
  no_build_required:
    description: "Whether the changes do not require a build"
    value: ${{ steps.result.outputs.no_build_required }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          no_build_required:
            - 'smoke-test*/**'
            - '*.md'
            - '*.yml'
          rest:
            - '!smoke-test*/**'
            - '!*.md'
            - '!*.yml'

    - id: result
      shell: bash
      run: |
        if [[ "${{ steps.changes.outputs.no_build_required }}" == "true" && "${{ steps.changes.outputs.rest }}" != "true" ]]; then
          echo "no_build_required=true" >> "$GITHUB_OUTPUT"
        else
          echo "no_build_required=false" >> "$GITHUB_OUTPUT"
        fi