[package]
name = "frontier-template-dancelight-emulated-chain"
description = "Frontier Template Dancelight emulated chain"
edition = "2021"
license = "GPL-3.0-only"
publish = false
version = "0.0.0"
[package.authors]
workspace = true

[lints]
workspace = true

[dependencies]
container-chain-template-simple-runtime  = { workspace = true, features = [ "std" ] }
emulated-integration-tests-common = { workspace = true }
sp-core = { workspace = true }
tanssi-emulated-integration-tests-common = { workspace = true }
xcm = { workspace = true }
xcm-emulator = { workspace = true }
