[package]
name = "frontier-template-dancelight-emulated-chain"
authors.workspace = true
edition = "2021"
license = "GPL-3.0-only"
version = "0.0.0"
description = "Frontier Template Dancelight emulated chain"
publish = false

[lints]
workspace = true

[dependencies]
sp-core = { workspace = true }
xcm = { workspace = true }
emulated-integration-tests-common = { workspace = true }
xcm-emulator = { workspace = true }
container-chain-template-simple-runtime  = { workspace = true, features = [ "std" ] }
tanssi-emulated-integration-tests-common = { workspace = true }