[package]
name = "tp-collator-assignment"
description = "Primitives relatd to collator-assignment"
edition = "2021"
version = "0.1.0"
authors = { workspace = true }
license = "GPL-3.0-only"


[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]
[dependencies]
hex-literal = { workspace = true }

log = { workspace = true }
serde = { workspace = true, optional = true, features = [ "derive" ] }
tp-traits = { workspace = true }

# Substrate
frame-support = { workspace = true, optional = true }
parity-scale-codec = { workspace = true }
scale-info = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true, optional = true }
sp-state-machine = { workspace = true, optional = true }
sp-std = { workspace = true }
sp-trie = { workspace = true, optional = true }

# Cumulus
cumulus-primitives-core = { workspace = true, optional = true }

# Polkadot
polkadot-primitives = { workspace = true, optional = true }

[features]
default = [ "std" ]
std = [ "cumulus-primitives-core/std", "frame-support/std", "parity-scale-codec/std", "polkadot-primitives", "serde/std", "sp-core/std", "sp-runtime/std", "sp-state-machine/std", "sp-std/std", "sp-trie/std", "tp-traits/std" ]
