[package]
name = "tp-chain-state-snapshot"
authors = { workspace = true }
description = "Primitives related to chain state snapshot"
edition = "2021"
license = "GPL-3.0-only"
version = "0.1.0"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]
[dependencies]

# Substrate
parity-scale-codec = { workspace = true }
sp-runtime = { workspace = true }
sp-state-machine = { workspace = true }
sp-trie = { workspace = true }

# Cumulus
cumulus-primitives-core = { workspace = true }

[features]
default = [ "std" ]
std = [ "cumulus-primitives-core/std", "parity-scale-codec/std", "sp-runtime/std", "sp-state-machine/std", "sp-trie/std" ]
