[package]
name = "westend-emulated-chain"
authors.workspace = true
edition = "2021"
license = "GPL-3.0-only"
version = "0.0.0"
description = "Westend emulated chain"
publish = false

[lints]
workspace = true

[dependencies]
westend-runtime = { workspace = true }
westend-runtime-constants = { workspace = true }

# Substrate
sc-consensus-grandpa = { workspace = true }
sp-authority-discovery = { workspace = true }
sp-consensus-babe = { workspace = true }
sp-consensus-beefy = { workspace = true, default-features = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-keyring = { workspace = true }
runtime-common = { workspace = true }
pallet-staking = { workspace = true }
runtime-parachains = { workspace = true }
cumulus-primitives-core = { workspace = true }

# Polkadot
polkadot-primitives = { workspace = true }
rococo-runtime = { workspace = true }
rococo-runtime-constants = { workspace = true }

# Cumulus
emulated-integration-tests-common = { workspace = true }
parachains-common = { workspace = true, default-features = true }

tanssi-emulated-integration-tests-common = { workspace = true }

[features]
default = [ "std" ]
std = [
    "westend-runtime/std",
    "westend-runtime-constants/std",
    "sp-authority-discovery/std",
    "sp-consensus-babe/std",
    "sp-consensus-beefy/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-keyring/std",
    "runtime-common/std",
    "pallet-staking/std",
    "runtime-parachains/std",
    "cumulus-primitives-core/std",
    "polkadot-primitives/std",
    "rococo-runtime/std",
    "rococo-runtime-constants/std",
    "parachains-common/std",
    "tanssi-emulated-integration-tests-common/std"
]
no_std = []