[package]
name = "westend-emulated-chain"
description = "Westend emulated chain"
edition = "2021"
license = "GPL-3.0-only"
publish = false
version = "0.0.0"
[package.authors]
workspace = true

[lints]
workspace = true

[dependencies]
westend-runtime = { workspace = true }
westend-runtime-constants = { workspace = true }

# Substrate
cumulus-primitives-core = { workspace = true }
pallet-staking = { workspace = true }
runtime-common = { workspace = true }
runtime-parachains = { workspace = true }
sc-consensus-grandpa = { workspace = true }
sp-authority-discovery = { workspace = true }
sp-consensus-babe = { workspace = true }
sp-consensus-beefy = { workspace = true, default-features = true }
sp-core = { workspace = true }
sp-keyring = { workspace = true }
sp-runtime = { workspace = true }

# Polkadot
polkadot-primitives = { workspace = true }
rococo-runtime = { workspace = true }
rococo-runtime-constants = { workspace = true }

# Cumulus
emulated-integration-tests-common = { workspace = true }
parachains-common = { workspace = true, default-features = true }

tanssi-emulated-integration-tests-common = { workspace = true }

[features]
default = [ "std" ]
std = [
	"cumulus-primitives-core/std",
	"pallet-staking/std",
	"parachains-common/std",
	"polkadot-primitives/std",
	"rococo-runtime-constants/std",
	"rococo-runtime/std",
	"runtime-common/std",
	"runtime-parachains/std",
	"sp-authority-discovery/std",
	"sp-consensus-babe/std",
	"sp-consensus-beefy/std",
	"sp-core/std",
	"sp-keyring/std",
	"sp-runtime/std",
	"tanssi-emulated-integration-tests-common/std",
	"westend-runtime-constants/std",
	"westend-runtime/std",
]
no_std = []
