[package]
name = "simple-template-dancelight-emulated-chain"
authors.workspace = true
edition = "2021"
license = "GPL-3.0-only"
version = "0.0.0"
description = "Dancelight emulated chain"
publish = false

[lints]
workspace = true

[dependencies]
sp-core = { workspace = true }
hex-literal = { workspace = true }
xcm = { workspace = true }
xcm-emulator = { workspace = true }
emulated-integration-tests-common = { workspace = true }
container-chain-template-frontier-runtime  = { workspace = true, features = [ "std" ] }