[package]
name = "simple-template-dancelight-emulated-chain"
authors.workspace = true
edition = "2021"
license = "GPL-3.0-only"
version = "0.0.0"
description = "Dancelight emulated chain"
publish = false

[lints]
workspace = true

[dependencies]
bitvec = { workspace = true }
log = { workspace = true }
parity-scale-codec = { workspace = true, features = [ "derive", "max-encoded-len" ] }
scale-info = { workspace = true, features = [ "derive" ] }
serde = { workspace = true }
serde_derive = { workspace = true, optional = true }
serde_json = { workspace = true, features = [ "alloc" ] }
smallvec = { workspace = true }
static_assertions = { workspace = true }

authority-discovery-primitives = { workspace = true }
babe-primitives = { workspace = true }
beefy-primitives = { workspace = true }
binary-merkle-tree = { workspace = true }
block-builder-api = { workspace = true }
dancelight-runtime-constants = { workspace = true }
dancelight-runtime = { workspace = true }
grandpa_primitives = { workspace = true }
inherents = { workspace = true }
offchain-primitives = { workspace = true }
sp-api = { workspace = true }
sp-application-crypto = { workspace = true }
sp-arithmetic = { workspace = true }
sp-consensus-aura = { workspace = true }
sp-core = { workspace = true }
sp-debug-derive = { workspace = true }
sp-genesis-builder = { workspace = true }
sp-io = { workspace = true }
sp-keystore = { workspace = true }
sp-mmr-primitives = { workspace = true }
sp-runtime = { workspace = true }
sp-session = { workspace = true }
sp-staking = { workspace = true }
sp-std = { workspace = true }
sp-storage = { workspace = true }
sp-trie = { workspace = true }
sp-version = { workspace = true }
tx-pool-api = { workspace = true }

frame-executive = { workspace = true }
frame-metadata-hash-extension = { workspace = true }
frame-support = { workspace = true, features = [ "tuples-96" ] }
frame-system = { workspace = true }
frame-system-rpc-runtime-api = { workspace = true }
nimbus-primitives = { workspace = true }
pallet-asset-rate = { workspace = true }
pallet-authority-assignment = { workspace = true }
pallet-authority-discovery = { workspace = true }
pallet-authority-mapping = { workspace = true }
pallet-authorship = { workspace = true }
pallet-babe = { workspace = true }
pallet-balances = { workspace = true }
pallet-beefy = { workspace = true }
pallet-beefy-mmr = { workspace = true }
pallet-collator-assignment = { workspace = true }
pallet-collective = { workspace = true }
pallet-conviction-voting = { workspace = true }
pallet-democracy = { workspace = true }
pallet-elections-phragmen = { workspace = true }
pallet-ethereum-token-transfers = { workspace = true }
pallet-external-validator-slashes = { workspace = true }
pallet-external-validators = { workspace = true }
pallet-external-validators-rewards = { workspace = true }
pallet-external-validators-rewards-runtime-api = { workspace = true }
pallet-grandpa = { workspace = true }
pallet-identity = { workspace = true }
pallet-initializer = { workspace = true }
pallet-invulnerables = { workspace = true }
pallet-membership = { workspace = true }
pallet-message-queue = { workspace = true }
pallet-mmr = { workspace = true }
pallet-multiblock-migrations = { workspace = true }
pallet-multisig = { workspace = true }
pallet-offences = { workspace = true }
pallet-parameters = { workspace = true }
pallet-preimage = { workspace = true }
pallet-proxy = { workspace = true }
pallet-ranked-collective = { workspace = true }
pallet-referenda = { workspace = true }
pallet-root-testing = { workspace = true }
pallet-scheduler = { workspace = true }
pallet-session = { workspace = true }
pallet-staking = { workspace = true }
pallet-sudo = { workspace = true }
pallet-timestamp = { workspace = true }
pallet-tips = { workspace = true }
pallet-transaction-payment = { workspace = true }
pallet-transaction-payment-rpc-runtime-api = { workspace = true }
pallet-treasury = { workspace = true }
pallet-utility = { workspace = true }
pallet-whitelist = { workspace = true }
pallet-xcm = { workspace = true }
pallet-xcm-benchmarks = { workspace = true, optional = true }

frame-benchmarking = { workspace = true, optional = true }
frame-system-benchmarking = { workspace = true, optional = true }
frame-try-runtime = { workspace = true, optional = true }
hex-literal = { workspace = true }

polkadot-parachain-primitives = { workspace = true }
primitives = { workspace = true }
runtime-common = { workspace = true }
runtime-parachains = { workspace = true }

xcm = { workspace = true }
xcm-builder = { workspace = true }
xcm-executor = { workspace = true }
xcm-runtime-apis = { workspace = true }

# Cumulus
cumulus-pallet-parachain-system = { workspace = true }
cumulus-primitives-core = { workspace = true }

# Tanssi
dp-consensus = { workspace = true }
dp-container-chain-genesis-data = { workspace = true }
tp-author-noting-inherent = { workspace = true }
tp-data-preservers-common = { workspace = true }
tp-stream-payment-common = { workspace = true }
tp-traits = { workspace = true }
tp-xcm-commons = { workspace = true }

pallet-author-noting = { workspace = true }
pallet-author-noting-runtime-api = { workspace = true }
pallet-configuration = { workspace = true }
pallet-data-preservers = { workspace = true }
pallet-inflation-rewards = { workspace = true }
pallet-outbound-message-commitment-recorder = { workspace = true }
pallet-pooled-staking = { workspace = true }
pallet-registrar = { workspace = true }
pallet-registrar-runtime-api = { workspace = true }
pallet-services-payment = { workspace = true }
pallet-services-payment-runtime-api = { workspace = true }
pallet-stream-payment = { workspace = true }
pallet-stream-payment-runtime-api = { workspace = true }
tanssi-runtime-common = { workspace = true }

# Moonkit
pallet-migrations = { workspace = true }

# Bridges
keyring = { workspace = true }
snowbridge-beacon-primitives = { workspace = true }
snowbridge-core = { workspace = true }
snowbridge-outbound-queue-runtime-api = { workspace = true }
snowbridge-pallet-ethereum-client = { workspace = true }
snowbridge-pallet-inbound-queue = { workspace = true }
snowbridge-pallet-inbound-queue-fixtures = { workspace = true, optional = true }
snowbridge-pallet-outbound-queue = { workspace = true }
snowbridge-pallet-system = { workspace = true }
snowbridge-router-primitives = { workspace = true }
tp-bridge = { workspace = true }
container-chain-template-simple-runtime  = { workspace = true, features = [ "std" ] }
xcm-emulator = { workspace = true }
tanssi-emulated-integration-tests-common = {workspace = true }
emulated-integration-tests-common = { workspace = true }
container-chain-template-frontier-runtime  = { workspace = true, features = [ "std" ] }

[dev-dependencies]
alloy-sol-types = { workspace = true, default-features = true }
finality-grandpa = { workspace = true, default-features = true, features = [ "derive-codec" ] }
milagro-bls = { workspace = true, features = [ "std" ] }
rand = { workspace = true, features = [ "std", "std_rng" ] }
remote-externalities = { workspace = true }
rococo-runtime = { workspace = true }
rococo-runtime-constants = { workspace = true }
sc-consensus-grandpa = { workspace = true }
separator = { workspace = true }
serde_json = { workspace = true }
sp-tracing = { workspace = true }
sp-trie = { workspace = true }
test-relay-sproof-builder = { workspace = true }
tiny-keccak = { workspace = true }
tokio = { workspace = true, features = [ "macros" ] }
westend-runtime = { workspace = true }
westend-runtime-constants = { workspace = true }
