[package]
name = "tanssi-emulated-integration-tests-common"
authors.workspace = true
edition = "2021"
license = "GPL-3.0-only"
version = "0.0.0"
description = "Common resources for integration testing with xcm-emulator"
publish = false

[lints]
workspace = true

[dependencies]
codec = { workspace = true }
hex-literal = { workspace = true }
paste = { workspace = true, default-features = true }

# Substrate
frame-support = { workspace = true, default-features = true }
pallet-assets = { workspace = true, default-features = true }
pallet-balances = { workspace = true, default-features = true }
pallet-message-queue = { workspace = true, default-features = true }
sc-consensus-grandpa = { workspace = true, default-features = true }
sp-authority-discovery = { workspace = true, default-features = true }
sp-core = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }
sp-std = { workspace = true }
babe-primitives = { workspace = true }
beefy-primitives = { workspace = true }

# Polkadot
pallet-xcm = { workspace = true, default-features = true }
polkadot-parachain-primitives = { workspace = true, default-features = true }
polkadot-primitives = { workspace = true, default-features = true }
polkadot-runtime-parachains = { workspace = true, default-features = true }
xcm = { workspace = true, default-features = true }
emulated-integration-tests-common = { workspace = true }
frame-system = { workspace = true }

# Cumulus
cumulus-pallet-parachain-system = { workspace = true, default-features = true }
cumulus-pallet-xcmp-queue = { workspace = true, default-features = true }
cumulus-primitives-core = { workspace = true, default-features = true }
parachains-common = { workspace = true, default-features = true }
xcm-emulator = { workspace = true, default-features = true }

# Bridges
snowbridge-pallet-outbound-queue = { workspace = true }
keyring = { workspace = true }
dancelight-runtime-constants = { workspace = true }
dancelight-runtime = { workspace = true }
