[package]
name = "tanssi-emulated-integration-tests-common"
authors.workspace = true
edition = "2021"
license = "GPL-3.0-only"
version = "0.0.0"
description = "Common resources for integration testing with xcm-emulator"
publish = false

[lints]
workspace = true

[dependencies]
# Substrate
frame-support = { workspace = true, default-features = true }
pallet-message-queue = { workspace = true, default-features = true }
sc-consensus-grandpa = { workspace = true, default-features = true }
sp-core = { workspace = true, default-features = true }
sp-std = { workspace = true }
babe-primitives = { workspace = true }

# Polkadot
xcm = { workspace = true, default-features = true }
frame-system = { workspace = true }

# Cumulus
cumulus-primitives-core = { workspace = true, default-features = true }
xcm-emulator = { workspace = true, default-features = true }

# Bridges
snowbridge-pallet-outbound-queue = { workspace = true }
keyring = { workspace = true }
dancelight-runtime = { workspace = true }

[features]
default = [ "std" ]
std = [
    "babe-primitives/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-message-queue/std",
    "sp-core/std",
    "sp-std/std",
    "xcm/std",
    "cumulus-primitives-core/std",
    "snowbridge-pallet-outbound-queue/std",
    "keyring/std",
    "dancelight-runtime/std"
]
no_std = []