[package]
name = "pallet-data-preservers-runtime-api"
authors = { workspace = true }
description = "Runtime API definition of pallet-data-preservers"
edition = "2021"
license = "GPL-3.0-only"
version = "0.1.0"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[lints]
workspace = true

[dependencies]
parity-scale-codec = { workspace = true }
scale-info = { workspace = true }
serde = { workspace = true, features = [ "derive" ] }
sp-api = { workspace = true }
thiserror = { workspace = true, optional = true }

[features]
default = [ "std" ]
std = [
	"parity-scale-codec/std",
	"scale-info/std",
	"serde/std",
	"sp-api/std",
	"thiserror",
]
