[package]
name = "tanssi-relay-service"
authors = { workspace = true }
description = "Utils to tie different Tanssi components together and allow instantiation of a node."
edition = "2021"
license = "GPL-3.0-only"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
# Substrate Client
babe = { workspace = true }
grandpa = { workspace = true }
pallet-transaction-payment-rpc = { workspace = true }
sc-authority-discovery = { workspace = true }
sc-basic-authorship = { workspace = true }
sc-block-builder = { workspace = true }
sc-chain-spec = { workspace = true }
sc-client-api = { workspace = true }
sc-client-db = { workspace = true }
sc-consensus = { workspace = true }
sc-consensus-manual-seal = { workspace = true }
sc-consensus-slots = { workspace = true }
sc-executor = { workspace = true }
sc-keystore = { workspace = true }
sc-network = { workspace = true }
sc-network-common = { workspace = true }
sc-network-sync = { workspace = true }
sc-offchain = { workspace = true }
sc-rpc-spec-v2 = { workspace = true }
sc-sync-state-rpc = { workspace = true }
sc-sysinfo = { workspace = true }
sc-transaction-pool = { workspace = true }
sc-transaction-pool-api = { workspace = true }
service = { workspace = true }
sp-mmr-primitives = { workspace = true }
substrate-frame-rpc-system = { workspace = true }
telemetry = { workspace = true }

# Substrate Primitives
beefy-primitives = { workspace = true }
consensus_common = { workspace = true }
pallet-transaction-payment = { workspace = true }
sp-api = { workspace = true }
sp-authority-discovery = { workspace = true }
sp-block-builder = { workspace = true }
sp-blockchain = { workspace = true }
sp-consensus-babe = { workspace = true }
sp-core = { workspace = true, features = [ "std" ] }
sp-inherents = { workspace = true, features = [ "std" ] }
sp-io = { workspace = true, features = [ "std" ] }
sp-keyring = { workspace = true }
sp-keystore = { workspace = true, features = [ "std" ] }
sp-offchain = { workspace = true, features = [ "std" ] }
sp-runtime = { workspace = true, features = [ "std" ] }
sp-session = { workspace = true }
sp-state-machine = { workspace = true }
sp-storage = { workspace = true }
sp-timestamp = { workspace = true }
sp-transaction-pool = { workspace = true }
sp-version = { workspace = true }
sp-weights = { workspace = true }

# Substrate Pallets
frame-system = { workspace = true }
pallet-babe = { workspace = true }
pallet-staking = { workspace = true }
pallet-transaction-payment-rpc-runtime-api = { workspace = true }

# Substrate Other
frame-benchmarking = { workspace = true }
frame-benchmarking-cli = { workspace = true }
frame-support = { workspace = true }
frame-system-rpc-runtime-api = { workspace = true }
prometheus-endpoint = { workspace = true }

# External Crates
async-io = { workspace = true }
async-trait = { workspace = true }
bitvec = { workspace = true, optional = true }
codec = { workspace = true }
futures = { workspace = true }
gum = { workspace = true }
hex-literal = { workspace = true }
is_executable = { workspace = true }
jsonrpsee = { workspace = true }
kvdb = { workspace = true }
kvdb-rocksdb = { workspace = true, optional = true }
log = { workspace = true }
parity-db = { workspace = true, optional = true }
parking_lot = { workspace = true }
schnellru = { workspace = true }
serde = { workspace = true, features = [ "derive" ] }
serde_json = { workspace = true }
thiserror = { workspace = true }

# Polkadot
polkadot-core-primitives = { workspace = true }
polkadot-node-core-parachains-inherent = { workspace = true }
polkadot-node-network-protocol = { workspace = true }
polkadot-node-primitives = { workspace = true }
polkadot-node-subsystem = { workspace = true }
polkadot-node-subsystem-types = { workspace = true }
polkadot-node-subsystem-util = { workspace = true }
polkadot-overseer = { workspace = true }
polkadot-parachain-primitives = { workspace = true }
polkadot-primitives = { workspace = true }
polkadot-rpc = { workspace = true }
polkadot-runtime-parachains = { workspace = true }

# Polkadot Runtime Constants
starlight-runtime-constants = { workspace = true, optional = true }

# Polkadot Runtimes
starlight-runtime = { workspace = true, optional = true }

# Polkadot Subsystems
polkadot-approval-distribution = { workspace = true, optional = true }
polkadot-availability-bitfield-distribution = { workspace = true, optional = true }
polkadot-availability-distribution = { workspace = true, optional = true }
polkadot-availability-recovery = { workspace = true, optional = true }
polkadot-collator-protocol = { workspace = true, optional = true }
polkadot-dispute-distribution = { workspace = true, optional = true }
polkadot-gossip-support = { workspace = true, optional = true }
polkadot-network-bridge = { workspace = true, optional = true }
polkadot-node-collation-generation = { workspace = true, optional = true }
polkadot-node-core-approval-voting = { workspace = true, optional = true }
polkadot-node-core-av-store = { workspace = true, optional = true }
polkadot-node-core-backing = { workspace = true, optional = true }
polkadot-node-core-bitfield-signing = { workspace = true, optional = true }
polkadot-node-core-candidate-validation = { workspace = true, optional = true }
polkadot-node-core-chain-api = { workspace = true, optional = true }
polkadot-node-core-chain-selection = { workspace = true, optional = true }
polkadot-node-core-dispute-coordinator = { workspace = true, optional = true }
polkadot-node-core-prospective-parachains = { workspace = true, optional = true }
polkadot-node-core-provisioner = { workspace = true, optional = true }
polkadot-node-core-pvf = { workspace = true, optional = true }
polkadot-node-core-pvf-checker = { workspace = true, optional = true }
polkadot-node-core-runtime-api = { workspace = true, optional = true }
polkadot-service = { workspace = true }
polkadot-statement-distribution = { workspace = true, optional = true }

xcm = { workspace = true }
xcm-runtime-apis = { workspace = true }

cumulus-primitives-core = { workspace = true }

# Own
dp-container-chain-genesis-data = { workspace = true, features = [ "json", "std" ] }
node-common = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
env_logger = { workspace = true }
polkadot-node-subsystem-test-helpers = { workspace = true }
polkadot-test-client = { workspace = true }
serial_test = { workspace = true }
tempfile = { workspace = true }
test-helpers = { workspace = true }

[features]
default = [ "db", "full-node" ]

db = [ "service/rocksdb" ]

full-node = [
	"kvdb-rocksdb",
	"parity-db",
	"polkadot-approval-distribution",
	"polkadot-availability-bitfield-distribution",
	"polkadot-availability-distribution",
	"polkadot-availability-recovery",
	"polkadot-collator-protocol",
	"polkadot-dispute-distribution",
	"polkadot-gossip-support",
	"polkadot-network-bridge",
	"polkadot-node-collation-generation",
	"polkadot-node-core-approval-voting",
	"polkadot-node-core-av-store",
	"polkadot-node-core-backing",
	"polkadot-node-core-bitfield-signing",
	"polkadot-node-core-candidate-validation",
	"polkadot-node-core-chain-api",
	"polkadot-node-core-chain-selection",
	"polkadot-node-core-dispute-coordinator",
	"polkadot-node-core-prospective-parachains",
	"polkadot-node-core-provisioner",
	"polkadot-node-core-pvf",
	"polkadot-node-core-pvf-checker",
	"polkadot-node-core-runtime-api",
	"polkadot-statement-distribution",
]

# Configure the native runtimes to use.
starlight-native = [ "bitvec", "starlight-runtime", "starlight-runtime-constants" ]

fast-runtime = [ "starlight-runtime?/fast-runtime" ]
runtime-benchmarks = [
	"cumulus-primitives-core/runtime-benchmarks",
	"frame-benchmarking-cli/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-babe/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"polkadot-parachain-primitives/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"polkadot-runtime-parachains/runtime-benchmarks",
	"polkadot-service/runtime-benchmarks",
	"polkadot-test-client/runtime-benchmarks",
	"sc-client-db/runtime-benchmarks",
	"service/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"starlight-runtime?/runtime-benchmarks",
	"xcm-runtime-apis/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-babe/try-runtime",
	"pallet-staking/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"polkadot-runtime-parachains/try-runtime",
	"polkadot-service/try-runtime",
	"sp-runtime/try-runtime",
	"starlight-runtime?/try-runtime",
]

malus = [ "full-node" ]
runtime-metrics = [
	"polkadot-runtime-parachains/runtime-metrics",
	"starlight-runtime?/runtime-metrics",
]

elastic-scaling-experimental = [
	"polkadot-collator-protocol?/elastic-scaling-experimental",
]
