[package]
name = "tanssi-relay-cli"
description = "Tanssi Relay-chain Client Node"
edition = "2021"
license = "GPL-3.0-only"
version = "0.1.0"

[lints]
workspace = true

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on Linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cfg-if = { workspace = true }
clap = { workspace = true, optional = true }
log = { workspace = true }
thiserror = { workspace = true }
futures = { workspace = true }
pyro = { workspace = true, optional = true }
pyroscope_pprofrs = { workspace = true, optional = true }

# polkadot-service = { workspace = true, optional = true }
service = { package = "polkadot-service", git = "https://github.com/moondance-labs/polkadot-sdk", branch = "tanssi-polkadot-v1.11.0", optional = true }
tanssi-relay-service = { workspace = true, optional = true }

sp-core = { workspace = true }
sp-io = { workspace = true }
sp-keyring = { workspace = true }
sp-maybe-compressed-blob = { workspace = true }
frame-benchmarking-cli = { workspace = true, optional = true }
sc-cli = { workspace = true, optional = true }
sc-service = { workspace = true, optional = true }
polkadot-node-metrics = { workspace = true }
polkadot-node-primitives = { workspace = true }
sc-tracing = { workspace = true, optional = true }
sc-sysinfo = { workspace = true }
sc-executor = { workspace = true }
sc-storage-monitor = { workspace = true }
sp-runtime = { workspace = true }

[build-dependencies]
substrate-build-script-utils = { workspace = true }

[features]
default = ["cli", "db", "full-node"]
db = ["service/db"]
cli = [
	"clap",
	"frame-benchmarking-cli",
	"sc-cli",
	"sc-service",
	"sc-tracing",
	"service",
	"tanssi-relay-service",
]
runtime-benchmarks = [
	"frame-benchmarking-cli?/runtime-benchmarks",
	"polkadot-node-metrics/runtime-benchmarks",
	"sc-service?/runtime-benchmarks",
	"service/runtime-benchmarks",
	"tanssi-relay-service/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
full-node = ["service/full-node"]
try-runtime = [
	"service/try-runtime",
	"tanssi-relay-service/try-runtime",
	"sp-runtime/try-runtime",
]
fast-runtime = ["service/fast-runtime", "tanssi-relay-service"]
pyroscope = ["pyro", "pyroscope_pprofrs"]

# Configure the native runtimes to use.
westend-native = ["service/westend-native"]
rococo-native = ["service/rococo-native"]
mozart-native = ["tanssi-relay-service/mozart-native"]

malus = ["full-node", "service/malus"]
runtime-metrics = [
	"polkadot-node-metrics/runtime-metrics",
	"service/runtime-metrics",
	"tanssi-relay-service/runtime-metrics",
]
