name: Typescript tests
description: |
  Setup and run the typescript tests against a local tanssi node and templates.

inputs:
  tanssi-binary:
    description: path to the tanssi binary
    required: true
  timeout:
    description: default timeout for the tests
    default: "5000"
  force-pass:
    description: "Indicate whether the workflow should mark the test step as successful, even if actual test failures occur."
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 7
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: "pnpm"
        cache-dependency-path: test/pnpm-lock.yaml
    - name: Set binary path and number of CPUs
      shell: bash
      run: |
        #### Ensure the tanssi binary is executable
        chmod uog+x ${{ inputs.tanssi-binary }}

        #### Set the binary path (absolute path to avoid subfolder working directories issues)
        echo "BINARY_PATH=$(realpath ${{ inputs.tanssi-binary }})" >> $GITHUB_ENV

        #### Set the number of CPUs to use for parallel tests.
        echo "CPUS=$(lscpu | egrep '^CPU\(s\)' | grep -o '[0-9]*')" >> $GITHUB_ENV

        echo "BINARY_PATH: $BINARY_PATH"
        echo "CPUS: $CPUS"

    - name: Install and run
      shell: bash
      run: |
        cd ./test
        pnpm install --frozen-lockfile
        pnpm moonwall test dev_tanssi || [[ '${{ inputs.force-pass }}' == 'true' ]]