name: Publish runtime docker image

inputs:
  tag:
    required: true
    type: string
  image:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Publish runtime docker image
      shell: bash
      run: |
        DOCKER_IMAGE=moondancelabs/${{ inputs.image }}
        DOCKER_TAG="${{ inputs.tag }}"
        COMMIT=`git rev-list -n 1 '${{ inputs.tag }}'`
        SHA=sha-${COMMIT::8}
        echo tagging "${DOCKER_IMAGE}:${SHA}"
        docker pull "${DOCKER_IMAGE}:${SHA}"
        docker tag "${DOCKER_IMAGE}:${SHA}" "${DOCKER_IMAGE}:${DOCKER_TAG}"
        docker push "${DOCKER_IMAGE}:${DOCKER_TAG}"
