[package]
name = "rococo-emulated-chain"
description = "Rococo emulated chain"
edition = "2021"
license = "GPL-3.0-only"
publish = false
version = "0.0.0"
[package.authors]
workspace = true

[lints]
workspace = true

[dependencies]
# Substrate
cumulus-primitives-core = { workspace = true }
polkadot-parachain-primitives = { workspace = true }
sc-consensus-grandpa = { workspace = true }
sp-consensus-babe = { workspace = true }
sp-consensus-beefy = { workspace = true, default-features = true }
sp-core = { workspace = true }

# Polkadot
rococo-runtime = { workspace = true }
rococo-runtime-constants = { workspace = true }

# Cumulus
emulated-integration-tests-common = { workspace = true }
runtime-parachains = { workspace = true }
tanssi-emulated-integration-tests-common = { workspace = true }
xcm-emulator = { workspace = true }


[features]
default = [ "std" ]
std = [
	"cumulus-primitives-core/std",
	"polkadot-parachain-primitives/std",
	"rococo-runtime-constants/std",
	"rococo-runtime/std",
	"runtime-parachains/std",
	"sp-consensus-babe/std",
	"sp-core/std",
]
no_std = []