# If you want standard clippy run:
# RUSTFLAGS= cargo clippy
[target.'cfg(feature = "cargo-clippy")']
rustflags = [
	"-Aclippy::erasing_op",         # E.g. 0 * DOLLARS
	"-Aclippy::identity_op",        # E.g. 1 * DOLLARS
	"-Aclippy::too-many-arguments", # (Turning this on would lead to)
	"-Aclippy::type_complexity",    # raison d'etre
	"-Dclippy::complexity",
	"-Dclippy::correctness",
	"-Dclippy::suspicious",
	"-Dunsafe_code",
]
