[package]
name = "tp-stream-payment-common"
authors = { workspace = true }
description = "Common stream payment types used by all runtimes"
edition = "2021"
license = "GPL-3.0-only"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
frame-support = { workspace = true }
frame-system = { workspace = true }
pallet-balances = { workspace = true }
pallet-stream-payment = { workspace = true }
pallet-timestamp = { workspace = true }
parity-scale-codec = { workspace = true }
primitives = { workspace = true }
scale-info = { workspace = true }
serde = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
tp-traits = { workspace = true }

[features]
default = [ "std" ]
std = [
	"frame-support/std",
	"frame-system/std",
	"pallet-balances/std",
	"pallet-stream-payment/std",
	"pallet-timestamp/std",
	"parity-scale-codec/std",
	"primitives/std",
	"scale-info/std",
	"serde/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
	"tp-traits/std",
]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-stream-payment/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"primitives/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"tp-traits/runtime-benchmarks",
]
