[package]
name = "frontier-template-emulated-chain"
description = "Frontier Template Dancelight emulated chain"
edition = "2021"
license = "GPL-3.0-only"
publish = false
version = "0.0.0"
[package.authors]
workspace = true

[lints]
workspace = true

[dependencies]
container-chain-template-frontier-runtime = { workspace = true, features = ["std"] }
cumulus-primitives-core = { workspace = true }
emulated-integration-tests-common = { workspace = true }
hex-literal = { workspace = true }
sp-core = { workspace = true }
xcm = { workspace = true }
xcm-emulator = { workspace = true }
frame-support = { workspace = true }