[[bin]]
name = "tanssi-relay"
path = "src/main.rs"

[[bin]]
name = "tanssi-relay-execute-worker"
path = "src/bin/execute-worker.rs"

[[bin]]
name = "tanssi-relay-prepare-worker"
path = "src/bin/prepare-worker.rs"

[package]
name = "tanssi-relay"
description = "Implementation of a `https://tanssi.network` node in Rust based on the Substrate framework."
license = "GPL-3.0-only"
rust-version = "1.64.0"
readme = "README.md"
edition = "2021"
version = "0.1.0"
default-run = "tanssi-relay"

[lints]
workspace = true

[dependencies]
color-eyre = { version = "0.6.1", default-features = false }
tikv-jemallocator = { version = "0.5.0", optional = true, features = ["unprefixed_malloc_on_supported_platforms"] }

# Crates in our workspace, defined as dependencies so we can pass them feature flags.
tanssi-relay-cli = { path = "cli", features = ["mozart-native"] }
polkadot-node-core-pvf = { workpace = true }
polkadot-node-core-pvf-prepare-worker = { workpace = true }
polkadot-overseer = { workspace = true }

# Needed for worker binaries.
polkadot-node-core-pvf-common = { workspace = true }
polkadot-node-core-pvf-execute-worker = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
tikv-jemallocator = { version = "0.5.0", features = ["unprefixed_malloc_on_supported_platforms"] }

[dev-dependencies]
assert_cmd = "2.0.4"
nix = { version = "0.26.1", features = ["signal"] }
tempfile = "3.2.0"
tokio = "1.37"
substrate-rpc-client = { workspace = true }
polkadot-core-primitives = { workspace = true }

[build-dependencies]
substrate-build-script-utils = { workspace = true }

[features]
runtime-benchmarks = ["tanssi-relay-cli/runtime-benchmarks"]
try-runtime = ["tanssi-relay-cli/try-runtime"]
fast-runtime = ["tanssi-relay-cli/fast-runtime"]
runtime-metrics = ["tanssi-relay-cli/runtime-metrics"]
pyroscope = ["tanssi-relay-cli/pyroscope"]
jemalloc-allocator = [
	"dep:tikv-jemallocator",
	"polkadot-node-core-pvf-prepare-worker/jemalloc-allocator",
	"polkadot-node-core-pvf/jemalloc-allocator",
	"polkadot-overseer/jemalloc-allocator",
]


# Enables timeout-based tests supposed to be run only in CI environment as they may be flaky
# when run locally depending on system load
ci-only-tests = ["polkadot-node-core-pvf/ci-only-tests"]

# Configuration for building a .deb package - for use with `cargo-deb`
[package.metadata.deb]
name = "tanssi-relay"
extended-description = "Implementation of a https://tanssi.network node in Rust based on the Substrate framework."
section = "misc"
maintainer = "security@parity.io"
license-file = ["LICENSE", "0"]
# https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html
maintainer-scripts = "scripts/packaging/deb-maintainer-scripts"
assets = [
	[
		"target/release/tanssi-relay",
		"/usr/bin/",
		"755",
	],
	[
		"target/release/tanssi-relay-prepare-worker",
		"/usr/lib/tanssi-relay/",
		"755",
	],
	[
		"target/release/tanssi-relay-execute-worker",
		"/usr/lib/tanssi-relay/",
		"755",
	],
	[
		"scripts/packaging/tanssi-relay.service",
		"/lib/systemd/system/",
		"644",
	],
]
conf-files = ["/etc/default/tanssi-relay"]

[package.metadata.spellcheck]
config = "./scripts/ci/gitlab/spellcheck.toml"
