[package]
name = "tanssi-relay"
default-run = "tanssi-relay"
description = "Implementation of a `https://tanssi.network` node in Rust based on the Substrate framework."
edition = "2021"
license = "GPL-3.0-only"
readme = "README.md"
rust-version = "1.64.0"
version = "0.1.0"

# Configuration for building a .deb package - for use with `cargo-deb`
[package.metadata.deb]
name = "tanssi-relay"
assets = [
	[
	"/usr/bin/",
	"755",
	"target/release/tanssi-relay",
],
	[
	"/usr/lib/tanssi-relay/",
	"755",
	"target/release/tanssi-relay-prepare-worker",
],
	[
	"/usr/lib/tanssi-relay/",
	"755",
	"target/release/tanssi-relay-execute-worker",
],
	[
	"/lib/systemd/system/",
	"644",
	"scripts/packaging/tanssi-relay.service",
],
]
conf-files = [ "/etc/default/tanssi-relay" ]
extended-description = "Implementation of a https://tanssi.network node in Rust based on the Substrate framework."
license-file = [ "0", "LICENSE" ]
maintainer = "security@tanssi.network"
# https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html
maintainer-scripts = "scripts/packaging/deb-maintainer-scripts"
section = "misc"
[[bin]]
name = "tanssi-relay"
path = "src/main.rs"

[[bin]]
name = "tanssi-relay-execute-worker"
path = "src/bin/execute-worker.rs"

[[bin]]
name = "tanssi-relay-prepare-worker"
path = "src/bin/prepare-worker.rs"

[lints]
workspace = true

[dependencies]
color-eyre = { workspace = true, default-features = false }
tikv-jemallocator = { workspace = true, optional = true, features = [ "unprefixed_malloc_on_supported_platforms" ] }

# Crates in our workspace, defined as dependencies so we can pass them feature flags.
polkadot-node-core-pvf = { workpace = true }
polkadot-node-core-pvf-prepare-worker = { workpace = true }
polkadot-overseer = { workspace = true }
tanssi-relay-cli = { workspace = true, features = [ "mozart-native" ] }

# Needed for worker binaries.
polkadot-node-core-pvf-common = { workspace = true }
polkadot-node-core-pvf-execute-worker = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
nix = { workspace = true, features = [ "signal" ] }
polkadot-core-primitives = { workspace = true }
substrate-rpc-client = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }

[build-dependencies]
substrate-build-script-utils = { workspace = true }

[features]
fast-runtime = [ "tanssi-relay-cli/fast-runtime" ]
jemalloc-allocator = [
	"dep:tikv-jemallocator",
	"polkadot-node-core-pvf-prepare-worker/jemalloc-allocator",
	"polkadot-node-core-pvf/jemalloc-allocator",
	"polkadot-overseer/jemalloc-allocator",
]
pyroscope = [ "tanssi-relay-cli/pyroscope" ]
runtime-benchmarks = [ "tanssi-relay-cli/runtime-benchmarks" ]
runtime-metrics = [ "tanssi-relay-cli/runtime-metrics" ]
try-runtime = [ "tanssi-relay-cli/try-runtime" ]


# Enables timeout-based tests supposed to be run only in CI environment as they may be flaky
# when run locally depending on system load
ci-only-tests = [ "polkadot-node-core-pvf/ci-only-tests" ]

[target."cfg(target_os = \"linux\")".dependencies]
tikv-jemallocator = { workspace = true, features = [ "unprefixed_malloc_on_supported_platforms" ] }
