[package]
name = "ccp-author-verifiability"
authors = { workspace = true }
description = "author verifiability primitives"
edition = "2021"
license = "GPL-3.0-only"
version = "0.1.0"

[dependencies]
# Substrate
frame-support = { workspace = true }
frame-system = { workspace = true }

sp-consensus-aura = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

# Nimbus
nimbus-primitives = { workspace = true }


[features]
default = [ "std" ]
std = [ "frame-support/std", "frame-system/std", "nimbus-primitives/std", "sp-consensus-aura/std", "sp-runtime/std", "sp-std/std"]