name: Zombienet Tests
description: |
  Downloads tanssi binaries compiled in previous step, and executes zombienet test suite using moonwall.
  Uploads zombienet logs as an artifact in case of failure.

inputs:
  test_name:
    description: Zombienet suite to run
    required: true

runs:
  using: "composite"
  steps:
    - name: Pnpm
      uses: pnpm/action-setup@v3.0.0
      with:
        version: 8

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: "pnpm"

    - name: "Download binaries"
      uses: actions/download-artifact@v4
      with:
        name: binaries
        path: target/release

    - name: "Run zombie test"
      shell: bash
      run: |
        chmod uog+x target/release/tanssi-node
        chmod uog+x target/release/tanssi-relay
        chmod uog+x target/release/tanssi-relay-prepare-worker
        chmod uog+x target/release/tanssi-relay-execute-worker
        chmod uog+x target/release/container-chain-simple-node
        chmod uog+x target/release/container-chain-frontier-node

        cd test
        pnpm install

        ## Run tests
        pnpm moonwall test ${{ inputs.test_name }}

    - name: "Gather zombie logs"
      if: failure()
      shell: bash
      run: |
        ls -ltr /tmp
        latest_zombie_dir=$(find /tmp -type d -iname "*zombie*" -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d" ")
        logs_dir="logs"
        mkdir -p "$logs_dir"
        pwd
        find "$latest_zombie_dir" -type f -name "*.log" -exec cp {} "$logs_dir" \;
        ls -ltr .

    - name: "Upload zombie logs"
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: logs-${{ inputs.test_name }}
        path: logs
