[package]
name = "dancelight-system-emulated-network"
authors.workspace = true
edition = "2021"
license = "GPL-3.0-only"
version = "0.0.0"
description = "Dancelight System emulated bridged network"
publish = false

[lints]
workspace = true

[dependencies]
dancelight-runtime = { workspace = true }
dancelight-runtime-constants = { workspace = true }
frame-support = { workspace = true, features = [ "tuples-96" ] }
snowbridge-pallet-outbound-queue = { workspace = true }
xcm-emulator = { workspace = true }
simple-template-dancelight-emulated-chain = { workspace = true }
frontier-template-dancelight-emulated-chain = { workspace = true }
dancelight-runtime-test-utils = { workspace = true }
tanssi-emulated-integration-tests-common = { workspace = true }
container-chain-template-frontier-runtime  = { workspace = true, features = [ "std" ] }
container-chain-template-simple-runtime  = { workspace = true, features = [ "std" ] }
cumulus-primitives-core = { workspace = true }
runtime-parachains = { workspace = true }

