[package]
name = "ccp-xcm"

authors = { workspace = true }
description = "container-chain xcm primitives"
edition = "2021"
license = "GPL-3.0-only"
version = "0.1.0"
[dependencies]

parity-scale-codec = { workspace = true, features = [ "derive", "max-encoded-len" ] }


# Substrate
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-core = { workspace = true }

sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }


# Polkadot
staging-xcm = { workspace = true }
staging-xcm-executor = { workspace = true }

[features]
default = [ "std" ]
std = [ "frame-support/std", "frame-system/std", "sp-core/std", "sp-io/std", "sp-std/std", "staging-xcm-executor/std", "staging-xcm/std" ]
