[package]
name = "tp-parathread-filter-common"
authors = { workspace = true }
description = "Common parathread filter types used by all runtimes supporting pallet-session and pallet-registrar"
edition = "2021"
license = "GPL-3.0-only"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
pallet-registrar = { workspace = true }
pallet-session = { workspace = true }
sp-std = { workspace = true }
tp-traits = { workspace = true }

[features]
default = [ "std" ]
std = [
	"pallet-registrar/std",
	"pallet-session/std",
	"sp-std/std",
	"tp-traits/std",
]
runtime-benchmarks = [
	"pallet-registrar/runtime-benchmarks",
	"tp-traits/runtime-benchmarks",
]
