[package]
name = "tp-author-noting-inherent-core"
authors = { workspace = true }
description = "primitives related to author-noting-inherent"
edition = "2021"
license = "GPL-3.0-only"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true, optional = true }
parity-scale-codec = { workspace = true, features = [ "derive", "max-encoded-len" ] }
scale-info = { workspace = true }

sp-core = { workspace = true }
sp-inherents = { workspace = true }
sp-trie = { workspace = true }

[features]
default = [ "std" ]
std = [
	"async-trait",
	"parity-scale-codec/std",
	"scale-info/std",
	"scale-info/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-trie/std",
]
