[package]
name = "tanssi-relay-encoder"
authors = { workspace = true }
description = "Allows to create encoded relay calls without depending on the relay runtime"
edition = "2021"
license = "GPL-3.0-only"
version = "0.1.0"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[lints]
workspace = true

[dependencies]
cumulus-primitives-core = { workspace = true }
parity-scale-codec = { workspace = true, features = [ "derive" ] }

[dev-dependencies]
polkadot-runtime-parachains = { workspace = true }
rococo-runtime = { workspace = true }
westend-runtime = { workspace = true }

[features]
default = [
	"std",
]
std = [
	"cumulus-primitives-core/std",
	"parity-scale-codec/std",
	"polkadot-runtime-parachains/std",
	"rococo-runtime/std",
	"westend-runtime/std",
]
