name: Bridge e2e tests
description: |
  Setup and run bridge e2e tests between tanssi and ethereum
  
inputs:
  node-version:
    description: which version of node to use
    required: false
    default: "22.x"

runs:
  using: "composite"
  steps:
    - name: Check g++
      shell: bash
      id: setup_g_plusplus
      run: |
        g++ --version
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
    - name: Check protoc
      shell: bash
      id: check_proto_c
      run: |
        protoc --version
    - name: Check jq
      shell: bash
      id: check_jq
      run: |
        jq --version
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.22.0'
        cache: false
    - name: Check go
      shell: bash
      id: check_go
      run: |
        go version
    - name: Run Mage
      uses: magefile/mage-action@v3
      with:
        install-only: true
    - name: Check mage
      shell: bash
      id: check_mage
      run: |
        mage --version

    - name: Cache Foundry
      uses: actions/cache@v3
      with:
        path: |
          ~/.foundry
          ~/.cache/foundry
        key: foundry-${{ runner.os }}-${{ hashFiles('**/foundry.toml', '**/remappings.txt') }}
        restore-keys: |
          foundry-${{ runner.os }}-

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
    - name: Check forge
      shell: bash
      id: check_forge
      run: |
        forge --version

    - name: Cache Symbiotic Contracts
      uses: actions/cache@v3
      id: cache-symbiotic
      with:
        path: |
          test/tmp/bridge/tanssi-symbiotic
          test/tmp/bridge/tanssi-symbiotic/out
          test/tmp/bridge/tanssi-symbiotic/cache
        key: symbiotic-${{ runner.os }}-${{ hashFiles('**/scripts/bridge/set-env.sh') }}
        restore-keys: |
          symbiotic-${{ runner.os }}-

    - name: Cache Snowbridge Relayer
      uses: actions/cache@v3
      id: cache-relayer
      with:
        path: |
          test/tmp/bridge/relayer
          test/tmp/bridge/relayer/snowbridge/contracts/out
          test/tmp/bridge/relayer/snowbridge/contracts/cache
        key: relayer-${{ runner.os }}-${{ hashFiles('**/scripts/bridge/set-env.sh') }}
        restore-keys: |
          relayer-${{ runner.os }}-
    - name: Prepare Bin Folders
      shell: bash
      run: |
        mkdir -p test/tmp/bridge/output/bin
    - name: Cache Ethereum Node Binaries
      uses: actions/cache@v3
      id: cache-ethereum-binaries
      with:
        path: |
          test/tmp/bridge/output/bin
        key: ethereum-bins-${{ runner.os }}-${{ hashFiles('**/scripts/bridge/set-env.sh') }}
        restore-keys: |
          ethereum-bins-${{ runner.os }}-

    - name: Pnpm
      uses: pnpm/action-setup@v4.0.0
      with:
        version: 9
        run_install: false
    - name: Install yarn
      shell: bash
      run: |-
        curl -fsSL --create-dirs -o $HOME/bin/yarn \
        https://github.com/yarnpkg/yarn/releases/download/v1.22.22/yarn-1.22.22.js
        chmod +x $HOME/bin/yarn
        echo "$HOME/bin" >> $GITHUB_PATH
    - name: Check yarn
      shell: bash
      id: check_yarn
      run: |
        yarn --version
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
    - name: Check date
      shell: bash
      id: check_date
      run: |
        date --version
    - name: Run Zombienet Test zombie_tanssi_relay_eth_bridge
      uses: ./.github/workflow-templates/zombienet-tests
      with:
        test_name: zombie_tanssi_relay_eth_bridge