[package]
name = "dancebox-emulated-chain"
description = "Dancebox emulated chain"
edition = "2021"
license = "GPL-3.0-only"
publish = false
version = "0.0.0"
[package.authors]
workspace = true

[lints]
workspace = true

[dependencies]
cumulus-primitives-core = { workspace = true }
dancebox-runtime = { workspace = true }
emulated-integration-tests-common = { workspace = true }
parity-scale-codec = { workspace = true }
polkadot-parachain-primitives = { workspace = true }
sp-consensus-aura = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
tanssi-emulated-integration-tests-common = { workspace = true }
xcm = { workspace = true }
xcm-builder = { workspace = true }
xcm-emulator = { workspace = true }
xcm-executor = { workspace = true }
