name: Create client release ticket
on:
  workflow_dispatch:
    inputs:
      from:
        description: "Previous client version (ex. v0.1.0)"
        required: true
      to:
        description: "Next client version (ex. v0.2.0)"
        required: true
      binary-type:
        description: "Binary type"
        type: choice
        options:
          - "parachain"
          - "solochain"

jobs:
  setup-scripts:
    runs-on: bare-metal
    steps:
      - uses: actions/checkout@v5
      - name: Upload tools
        uses: actions/upload-artifact@v4
        with:
          name: original-tools
          path: tools

  create_client_ticket:
    needs: ["setup-scripts"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Download Original Tools
        uses: actions/download-artifact@v5
        with:
          name: original-tools
          path: original-tools
      - name: Generate client release issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: original-tools
        run: |
          npm i
          npm run --silent print-client-release-issue -- --chainType ${{ github.event.inputs.binary-type }} --from ${{ github.event.inputs.from }} --to ${{ github.event.inputs.to }} | tee ../client-release-issue.md
      - name: Create version bump issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: ${{ github.event.inputs.binary-type }} client ${{ github.event.inputs.to }} release
          content-filepath: ./client-release-issue.md
          labels: |
            automated issue