name: Publish Docker runtime containers

on:
  workflow_dispatch:
    inputs:
      tag:
        description: runtime tag (ex. runtime-2200-templates) to publish on docker
        required: true

jobs:
  tag-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ["container-chain-simple-template", "container-chain-evm-template"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to DockerHub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish runtime docker image
        uses: ./.github/workflow-templates/publish-runtime-docker
        with:
          image: ${{matrix.image}}
          tag: ${{ github.event.inputs.tag }}