name: Publish Docker Solochain

on:
  workflow_dispatch:
    inputs:
      tag:
        description: tag (ex. v0.8.3) to publish on docker
        required: true

env:
  BASE_URL: https://github.com/moondance-labs/tanssi/releases/download
jobs:
  tag-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [
          { name: "starlight", file_name: "tanssi-relay" },
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4 
        with:
          fetch-depth: 0
      - name: Login to DockerHub
        uses: docker/login-action@v3.4.0  
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download files
        run: |
          mkdir -p build
          VERSION="${{ github.event.inputs.tag }}"
          wget "${{ env.BASE_URL }}/$VERSION/${{ matrix.image.file_name }}" -O build/${{ matrix.image.file_name }}
          wget "${{ env.BASE_URL }}/$VERSION/${{ matrix.image.file_name }}-execute-worker" -O build/${{ matrix.image.file_name }}-execute-worker
          wget "${{ env.BASE_URL }}/$VERSION/${{ matrix.image.file_name }}-prepare-worker" -O build/${{ matrix.image.file_name }}-prepare-worker

          wget "${{ env.BASE_URL }}/$VERSION/${{ matrix.image.file_name }}-skylake" -O build/${{ matrix.image.file_name }}-skylake
          wget "${{ env.BASE_URL }}/$VERSION/${{ matrix.image.file_name }}-execute-worker-skylake" -O build/${{ matrix.image.file_name }}-execute-worker-skylake
          wget "${{ env.BASE_URL }}/$VERSION/${{ matrix.image.file_name }}-prepare-worker-skylake" -O build/${{ matrix.image.file_name }}-prepare-worker-skylake

          wget "${{ env.BASE_URL }}/$VERSION/${{ matrix.image.file_name }}-znver3" -O build/${{ matrix.image.file_name }}-znver3
          wget "${{ env.BASE_URL }}/$VERSION/${{ matrix.image.file_name }}-execute-worker-znver3" -O build/${{ matrix.image.file_name }}-execute-worker-znver3
          wget "${{ env.BASE_URL }}/$VERSION/${{ matrix.image.file_name }}-prepare-worker-znver3" -O build/${{ matrix.image.file_name }}-prepare-worker-znver3

      - name: Publish Node docker image
        uses: ./.github/workflow-templates/publish-node-docker
        with:
          image: ${{matrix.image.name}}
          tag: ${{ github.event.inputs.tag }}