name: Update Typescript API Augment

on:
  issue_comment:
    types: [ created ]
  # TODO: REMOVE AFTER TEST
  push:
    branches:
      - MD-884-*

jobs:
  update_typescript_api_augment:
    # TODO: Test once it merged to main
    #    if: ${{ github.event.comment.body && contains(github.event.comment.body, '/update-api-augment') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check CoreDev membership
        id: check-coredev
        run: |
          response=$(curl -s -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/orgs/moondance-labs/team/coredev/memberships/${{ github.actor }})
          
          echo "response: $response"
          
          if [[ "$(echo $response | jq -r '.state')" != "active" ]]; then
          echo "Not a CoreDev member!"
          exit 1
          fi

      - name: Proceed if CoreDev member
        if: ${{ steps.check-coredev.outcome == 'success' }}
        run: echo "User is a CoreDev member and can trigger the job."
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.set-tags.outputs.git_ref }}

      - name: Cargo build
        uses: ./.github/workflow-templates/cargo-build
        with:
          features: "fast-runtime"

      - name: "Download binaries"
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: target/release

      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "pnpm"

      - name: "Generate Local interfaces"
        run: |
          chmod uog+x target/release/tanssi-node
          chmod uog+x target/release/tanssi-relay
          cd typescript-api
          pnpm ci
          pnpm create-local-interfaces

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "Auto-generated TypeScript interfaces"
            git push origin HEAD:${{ github.head_ref }}
          fi