name: Update Typescript API Augment by Comment Command

on:
  issue_comment:
    types: [ created ]
  # TODO: REMOVE AFTER TEST
  push:
    branches:
      - MD-884-*

permissions:
  contents: write

jobs:
  update_typescript_api_augment:
    env:
      TMP_TARGET: "/tmp/target"
      CARGO_TARGET_DIR: "target"
      RUSTC_WRAPPER: "sccache"
      CARGO_INCREMENTAL: "0"
      SCCACHE_CACHE_SIZE: "100GB"
      SCCACHE_GHA_ENABLED: "true"
    # TODO: Test once it merged to main
    #    if: github.event.comment.body == '/generate-ts-api' }}
    runs-on: self-hosted
    steps:
      - name: Check Permission via GraphQL
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG: moondance-labs
          REPO: tanssi
          COLLABORATOR: ${{ github.actor }}
        run: |
          permissions=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$ORG/$REPO/collaborators/$COLLABORATOR/permission")
          
          permission_level=$(echo "$permissions" | jq -r '.permission')
          
          if [[ "$permission_level" == "write" || "$permission_level" == "admin" ]]; then
            echo "✅ User $COLLABORATOR has permission: "$permission_level". Proceeding..."
          else
            echo "❌ User $COLLABORATOR doesn't have permission: "$permission_level". Failing..." && exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.set-tags.outputs.git_ref }}

      - name: Cargo build
        uses: ./.github/workflow-templates/cargo-build
        with:
          features: "fast-runtime"

      - name: Pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 9

      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "pnpm"

      - name: "Generate Local interfaces"
        run: |
          chmod uog+x target/release/tanssi-node
          chmod uog+x target/release/tanssi-relay
          cd typescript-api
          pnpm install --frozen-lockfile
          pnpm create-local-interfaces

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            cd typescript-api
            git add .
            echo "About to commit changes"
            git commit -m "Auto-generated TypeScript interfaces"
            echo "About to push changes"
            response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/actions/permissions)
            echo "Actions permissions: $response"
            git push -u origin $(git branch --show-current)
          fi