[package]
name = "rococo-system-emulated-network"
description = "Rococo System emulated bridged network"
edition = "2021"
license = "GPL-3.0-only"
publish = false
version = "0.0.0"
[package.authors]
workspace = true

[lints]
workspace = true

[dependencies]
container-chain-template-simple-runtime  = { workspace = true, features = [ "std" ] }
frame-support = { workspace = true, features = [ "tuples-96" ] }
snowbridge-pallet-outbound-queue = { workspace = true }
sp-keyring = { workspace = true }
tanssi-emulated-integration-tests-common = { workspace = true }
xcm-emulator = { workspace = true }
frontier-template-emulated-chain = { workspace = true }
simple-template-emulated-chain = { workspace = true }
rococo-emulated-chain = { workspace = true }
cumulus-primitives-core = { workspace = true }
dancebox-rococo-emulated-chain = { workspace = true }
dancebox-emulated-chain = { workspace = true }