name: Install frame-omni-bencher
description: |
  Install frame-omni-bencher

runs:
  using: "composite"
  steps:
    - name: Install frame-omni-bencher
      shell: bash
      run: |
        cargo install frame-omni-bencher --locked --git https://github.com/moondance-labs/polkadot-sdk --branch tanssi-polkadot-stable2506 --force
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH