name: Install frame-omni-bencher
description: |
  Install frame-omni-bencher

runs:
  using: "composite"
  steps:
    - name: Install frame-omni-bencher
      shell: bash
      run: |
        BRANCH=$(grep -m1 'moondance-labs/polkadot-sdk' Cargo.lock \
          | sed -E 's/.*branch=([^#"]+).*/\1/')
        cargo install frame-omni-bencher --locked --git https://github.com/moondance-labs/polkadot-sdk --branch $BRANCH --force
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH