name: Install frame-omni-bencher
description: |
  Install frame-omni-bencher

runs:
  using: "composite"
  steps:
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.9

    - name: Setup Variables
      shell: bash
      run: |
        echo "CARGO_INCREMENTAL=0" >> $GITHUB_ENV
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
        echo "SCCACHE_CACHE_SIZE=100GB" >> $GITHUB_ENV  
        # Set RUSTFLAGS if not already set
        if [ -z "$RUSTFLAGS" ]; then
          echo "RUSTFLAGS=-C opt-level=3 -D warnings -C linker=clang -C link-arg=-fuse-ld=$(pwd)/mold/bin/mold" >> $GITHUB_ENV
        fi

    - name: Setup Mold Linker
      shell: bash
      run: |
        mkdir -p mold
        wget https://github.com/rui314/mold/releases/download/v2.30.0/mold-2.30.0-$(uname -m)-linux.tar.gz -O - | tar -C $(realpath mold) --strip-components=1 -xzf -
    # With rustup's nice new toml format, we just need to run rustup show to install the toolchain
    # https://github.com/actions-rs/toolchain/issues/126#issuecomment-782989659

    - name: Setup Rust toolchain
      shell: bash
      run: |
        if ! which "rustup" > /dev/null; then
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        fi
        rustup show

    - name: Install frame-omni-bencher
      shell: bash
      run: |
        BRANCH=$(grep -m1 'moondance-labs/polkadot-sdk' Cargo.lock \
          | sed -E 's/.*branch=([^#"]+).*/\1/')
        cargo install frame-omni-bencher --locked --git https://github.com/moondance-labs/polkadot-sdk --branch $BRANCH --force
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH